#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = "#FFFFFF"
	weight = 5950
	growthFactor = 1
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 1
	numAffixes = 1
	defaultColor = "#FFC0CB"
	weight = 40
	growthFactor = 1
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = "#FFFF00"
	weight = 7
	growthFactor = 2
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 3
	numAffixes = 3
	defaultColor = "#FF9900"
	weight = 1
	growthFactor = 3
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 4
	numAffixes = 3
	defaultColor = "#66FFFF"
	weight = 1
	growthFactor = 4
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 5
	numAffixes = 4
	defaultColor = "#CC33FF"
	weight = 0
	growthFactor = 5
	effects = []
	presetAffixes = []
